# Generated by Django 2.1.4 on 2018-12-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('employee_id', models.CharField(max_length=15)),
                ('complain_request', models.TextField(max_length=100)),
            ],
        ),
    ]
